namespace SpriteKind {
    export const moneda = SpriteKind.create()
    export const Meta = SpriteKind.create()
}
function Empezar_nivel (nºmonedas: number) {
    sprites.destroyAllSpritesOfKind(SpriteKind.moneda)
    tiles.placeOnRandomTile(tiburon, assets.tile`myTile1`)
    tiles.placeOnRandomTile(mono, assets.tile`myTile2`)
    todos_delfines()
    for (let index = 0; index < nºmonedas; index++) {
        moneda = sprites.create(img`
            . . b b b b . . 
            . b 5 5 5 5 b . 
            b 5 d 3 3 d 5 b 
            b 5 3 5 5 1 5 b 
            c 5 3 5 5 1 d c 
            c d d 1 1 d d c 
            . f d d d d f . 
            . . f f f f . . 
            `, SpriteKind.moneda)
        animation.runImageAnimation(
        moneda,
        [img`
            . . b b b b . . 
            . b 5 5 5 5 b . 
            b 5 d 3 3 d 5 b 
            b 5 3 5 5 1 5 b 
            c 5 3 5 5 1 d c 
            c d d 1 1 d d c 
            . f d d d d f . 
            . . f f f f . . 
            `,img`
            . . . b b . . . 
            . . b 5 5 b . . 
            . b 5 d 1 5 b . 
            . b 5 3 1 5 b . 
            . c 5 3 1 d c . 
            . c 5 1 d d c . 
            . . f d d f . . 
            . . . f f . . . 
            `,img`
            . . . b b . . . 
            . . b 5 5 b . . 
            . . b 1 1 b . . 
            . . b 5 5 b . . 
            . . b d d b . . 
            . . c d d c . . 
            . . c 3 3 c . . 
            . . . f f . . . 
            `,img`
            . . . b b . . . 
            . . b 5 5 b . . 
            . b 5 1 d 5 b . 
            . b 5 1 3 5 b . 
            . c d 1 3 5 c . 
            . c d d 1 5 c . 
            . . f d d f . . 
            . . . f f . . . 
            `],
        150,
        true
        )
        tiles.placeOnRandomTile(moneda, assets.tile`myTile0`)
    }
    scene.cameraFollowSprite(tiburon)
}
function daño () {
    info.changeLifeBy(-1)
    tiles.placeOnRandomTile(tiburon, assets.tile`myTile1`)
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    if (dirección == "izquierda") {
        tiburon.setImage(img`
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ..............ccffff................
            .............cddbbbf................
            ......ffffffcddbbbf.................
            ....ffbbbbbbbbbbbbbffff.......ccccc.
            ..ffbbbbbbbbcbcbbbfffffff....cdbbbc.
            .fbbbbbbbbbbcbbcbbffffffffffcddbbc..
            fbcbbbbbbbbbbcbcbbffffffffffbdbbf...
            fbbbbbbbfffbbcbbbbfffffffffffbbcf...
            ffbb1111fffbbcbbbbfffffffffffbccf...
            .ff111111111bbbbcc11fffffff..fbbcf..
            ...ccccccc111bdbbb222ffff.....ffbbf.
            .......ccccccfbdbbbfff..........fff.
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            `)
    } else {
        tiburon.setImage(img`
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ................ffffcc..............
            ................fbbbddc.............
            .................fbbbddcffffff......
            .ccccc.......ffffbbbbbbbbbbbbbff....
            .cbbbdc....fffffffbbbcbcbbbbbbbbff..
            ..cbbddcffffffffffbbcbbcbbbbbbbbbbf.
            ...fbbdbffffffffffbbcbcbbbbbbbbbbcbf
            ...fcbbfffffffffffbbbbcbbfffbbbbbbbf
            ...fccbfffffffffffbbbbcbbfff1111bbff
            ..fcbbf..fffffff11ccbbbb111111111ff.
            .fbbff.....ffff222bbbdb111ccccccc...
            .fff..........fffbbbdbfcccccc.......
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            ....................................
            `)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Meta, function (sprite, otherSprite) {
    effects.hearts.startScreenEffect(500)
    nivel += 1
    if (nivel == 1) {
        tiles.setCurrentTilemap(tilemap`nivel10`)
        Empezar_nivel(83)
    } else {
        game.setGameOverScoringType(game.ScoringType.None)
        game.gameOver(true)
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    dirección = "derecha"
    animation.runImageAnimation(
    tiburon,
    [img`
        ..............fffc..............
        ..............fbddcc............
        ..ccc.........ffbddbc...........
        ..cbbc.........fcbbccf..........
        ...cbdc.......ffccccccfffffff...
        ...fbdc....fffffbbbbbbbbbbbbcff.
        ....fbdc.fffffffbbbbcbbbbbbbbbcf
        ....fcdfffffffffbcbcbbbffbbbbcbf
        ....fcbbcfffffffbcbcbbbff1111bbf
        ...fcbbcffffffffbbcbb11111111bf.
        ...fbbffffffff11bbbb11bc33cccf..
        ..fbbf..fffff222cbbb111c131cf...
        ..fff....fffff11ccbbc111c33f....
        ..........fffffccbbdf1111ff.....
        ............ffbbbbdffffff.......
        ..............fffffbf...........
        ..............cbf..cbf..........
        .............cbf...cbf..........
        .............cbf....cbff........
        ............cbff....cbbbf.......
        ............cbbbf....ccc........
        .............ccc................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ..............fffc..............
        ..............fbddcc............
        ..ccc.........ffbddbc...........
        ..cbbc.........fcbbccf..........
        ...cbdc.......ffccccccfffffff...
        ...fbdc....fffffbbbbbbbbbbbbcff.
        ....fbdc.fffffffbbbbcbbbbbbbbbcf
        ....fcdfffffffffbcbcbbbffbbbbcbf
        ....fcbbcfffffffbcbcbbbff1111bbf
        ...fcbbcffffffffbbcbb11111111bf.
        ...fbbffffffff11bbbb11bc33cccf..
        ..fbbf..fffff222cbbb111c131cf...
        ..fff....fffff11ccbbc111c33f....
        ..........fffffccbbdf1111ff.....
        ............ffbbbbdffffff.......
        ..............fffffbf...........
        ..............cbf.cbf...........
        ..............cbf.cbf...........
        ..............cbf.cbf...........
        ..............cbffcbff..........
        ..............cbbbfbbbf.........
        ...............ccc.ccc..........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ..............fffc..............
        ..............fbddcc............
        ..ccc.........ffbddbc...........
        ..cbbc.........fcbbccf..........
        ...cbdc.......ffccccccfffffff...
        ...fbdc....fffffbbbbbbbbbbbbcff.
        ....fbdc.fffffffbbbbcbbbbbbbbbcf
        ....fcdfffffffffbcbcbbbffbbbbcbf
        ....fcbbcfffffffbcbcbbbff1111bbf
        ...fcbbcffffffffbbcbb11111111bf.
        ...fbbffffffff11bbbb11bc33cccf..
        ..fbbf..fffff222cbbb111c131cf...
        ..fff....fffff11ccbbc111c33f....
        ..........fffffccbbdf1111ff.....
        ............ffbbbbdffffff.......
        ..............fffffbf...........
        ..............cbfcbf............
        ...............cbfbf............
        ...............ccbff............
        ..............cbcbbbf...........
        ..............cbbccc............
        ...............ccc..............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ..............fffc..............
        ..............fbddcc............
        ..ccc.........ffbddbc...........
        ..cbbc.........fcbbccf..........
        ...cbdc.......ffccccccfffffff...
        ...fbdc....fffffbbbbbbbbbbbbcff.
        ....fbdc.fffffffbbbbcbbbbbbbbbcf
        ....fcdfffffffffbcbcbbbffbbbbcbf
        ....fcbbcfffffffbcbcbbbff1111bbf
        ...fcbbcffffffffbbcbb11111111bf.
        ...fbbffffffff11bbbb11bc33cccf..
        ..fbbf..fffff222cbbb111c131cf...
        ..fff....fffff11ccbbc111c33f....
        ..........fffffccbbdf1111ff.....
        ............ffbbbbdffffff.......
        ..............fffffbf...........
        ..............cbf.cbf...........
        ..............cbf.cbf...........
        ..............cbf.cbf...........
        ..............cbffcbff..........
        ..............cbbbfbbbf.........
        ...............ccc.ccc..........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `],
    150,
    true
    )
})
function crear_delfin (delfin: Sprite) {
    animation.runImageAnimation(
    delfin,
    [img`
        . . . . . . . . . f f . . . . . 
        . . . . . . . . f 6 f . . . . . 
        . . . . . f f f 6 6 f f . . . . 
        . . . . f 6 6 6 8 8 8 6 f . . . 
        . . . f 6 1 1 8 8 8 8 8 6 f . . 
        . . f f 6 f 1 8 8 8 8 8 8 6 f . 
        . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
        . . f f f f f f 6 6 f 8 8 8 6 f 
        . . . . . . 8 6 f 6 f f 8 8 8 f 
        . . . . . . 8 f 8 f f . f 8 8 f 
        . . . . . 8 . . 8 . . . f 8 f . 
        . . . 8 . 8 . . . 8 . f f 8 f . 
        . . . 8 8 . . . . 8 f 8 8 f . . 
        . . . . . . . . . . 8 f 8 f . . 
        . . . . . . . . . 8 8 . f . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . f f . . . . . 
        . . . . . . . . f 6 f . . . . . 
        . . . . . f f f 6 6 f f . . . . 
        . . . . f 6 6 6 8 8 8 6 f . . . 
        . . . f 6 1 1 8 8 8 8 8 6 f . . 
        . . f f 6 f 1 8 8 8 8 8 8 6 f . 
        . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
        . . f f f f f f 6 6 f 8 8 8 6 f 
        . . . . . . 8 6 f 6 f f 8 8 8 f 
        . . . . . . 8 f 8 f f . f 8 8 f 
        . . . . . . 8 . 8 . . . f 8 f . 
        . . . . . . 8 . 8 . . f f 8 f . 
        . . . . . . 8 . 8 . f 8 8 f . . 
        . . . . . . 8 . 8 . . f 8 f . . 
        . . . . . 8 8 8 8 . . . f . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . f f . . . . . 
        . . . . . . . . f 6 f . . . . . 
        . . . . . f f f 6 6 f f . . . . 
        . . . . f 6 6 6 8 8 8 6 f . . . 
        . . . f 6 1 1 8 8 8 8 8 6 f . . 
        . . f f 6 f 1 8 8 8 8 8 8 6 f . 
        . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
        . . f f f f f f 6 6 f 8 8 8 6 f 
        . . . . . . 8 6 f 6 f f 8 8 8 f 
        . . . . . . 8 f 8 f f . f 8 8 f 
        . . . . . . . 8 . . . . f 8 f . 
        . . . . . 8 . 8 . . . f f 8 f . 
        . . . . . 8 8 . 8 . f 8 8 f . . 
        . . . . . . . . . 8 . f 8 f . . 
        . . . . . . . . 8 8 . . f . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . f f . . . . . 
        . . . . . . . . f 6 f . . . . . 
        . . . . . f f f 6 6 f f . . . . 
        . . . . f 6 6 6 8 8 8 6 f . . . 
        . . . f 6 1 1 8 8 8 8 8 6 f . . 
        . . f f 6 f 1 8 8 8 8 8 8 6 f . 
        . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
        . . f f f f f f 6 6 f 8 8 8 6 f 
        . . . . . . 8 6 f 6 f f 8 8 8 f 
        . . . . . . 8 f 8 f f . f 8 8 f 
        . . . . . . 8 . 8 . . . f 8 f . 
        . . . . . . 8 . 8 . . f f 8 f . 
        . . . . . . 8 . 8 . f 8 8 f . . 
        . . . . . . 8 . 8 . . f 8 f . . 
        . . . . . 8 8 8 8 . . . f . . . 
        . . . . . . . . . . . . . . . . 
        `],
    150,
    true
    )
    tiles.placeOnRandomTile(delfin, assets.tile`myTile15`)
    delfin.y += -1
    delfin.vx = -50
    delfin.ay = 300
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    dirección = "izquierda"
    animation.runImageAnimation(
    tiburon,
    [img`
        ..............cfff..............
        ............ccddbf..............
        ...........cbddbff.........ccc..
        ..........fccbbcf.........cbbc..
        ...fffffffccccccff.......cdbc...
        .ffcbbbbbbbbbbbbfffff....cdbf...
        fcbbbbbbbbbcbbbbfffffff.cdbf....
        fbcbbbbffbbbcbcbfffffffffdcf....
        fbb1111ffbbbcbcbfffffffcbbcf....
        .fb11111111bbcbbffffffffcbbcf...
        ..fccc33cb11bbbb11ffffffffbbf...
        ...fc131c111bbbc222fffff..fbbf..
        ....f33c111cbbcc11fffff....fff..
        .....ff1111fdbbccfffff..........
        .......ffffffdbbbbff............
        ...........fbfffff..............
        ..........fbc..fbc..............
        ..........fbc...fbc.............
        ........ffbc....fbc.............
        .......fbbbc....ffbc............
        ........ccc....fbbbc............
        ................ccc.............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ..............cfff..............
        ............ccddbf..............
        ...........cbddbff.........ccc..
        ..........fccbbcf.........cbbc..
        ...fffffffccccccff.......cdbc...
        .ffcbbbbbbbbbbbbfffff....cdbf...
        fcbbbbbbbbbcbbbbfffffff.cdbf....
        fbcbbbbffbbbcbcbfffffffffdcf....
        fbb1111ffbbbcbcbfffffffcbbcf....
        .fb11111111bbcbbffffffffcbbcf...
        ..fccc33cb11bbbb11ffffffffbbf...
        ...fc131c111bbbc222fffff..fbbf..
        ....f33c111cbbcc11fffff....fff..
        .....ff1111fdbbccfffff..........
        .......ffffffdbbbbff............
        ...........fbfffff..............
        ...........fbc.fbc..............
        ...........fbc.fbc..............
        ...........fbc.fbc..............
        ..........ffbcffbc..............
        .........fbbbfbbbc..............
        ..........ccc.ccc...............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ..............cfff..............
        ............ccddbf..............
        ...........cbddbff.........ccc..
        ..........fccbbcf.........cbbc..
        ...fffffffccccccff.......cdbc...
        .ffcbbbbbbbbbbbbfffff....cdbf...
        fcbbbbbbbbbcbbbbfffffff.cdbf....
        fbcbbbbffbbbcbcbfffffffffdcf....
        fbb1111ffbbbcbcbfffffffcbbcf....
        .fb11111111bbcbbffffffffcbbcf...
        ..fccc33cb11bbbb11ffffffffbbf...
        ...fc131c111bbbc222fffff..fbbf..
        ....f33c111cbbcc11fffff....fff..
        .....ff1111fdbbccfffff..........
        .......ffffffdbbbbff............
        ...........fbfffff..............
        ............fbcfbc..............
        ............fbfbc...............
        ............ffbcc...............
        ...........fbbbcbc..............
        ............cccbbc..............
        ..............ccc...............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ..............cfff..............
        ............ccddbf..............
        ...........cbddbff.........ccc..
        ..........fccbbcf.........cbbc..
        ...fffffffccccccff.......cdbc...
        .ffcbbbbbbbbbbbbfffff....cdbf...
        fcbbbbbbbbbcbbbbfffffff.cdbf....
        fbcbbbbffbbbcbcbfffffffffdcf....
        fbb1111ffbbbcbcbfffffffcbbcf....
        .fb11111111bbcbbffffffffcbbcf...
        ..fccc33cb11bbbb11ffffffffbbf...
        ...fc131c111bbbc222fffff..fbbf..
        ....f33c111cbbcc11fffff....fff..
        .....ff1111fdbbccfffff..........
        .......ffffffdbbbbff............
        ...........fbfffff..............
        ...........fbc.fbc..............
        ...........fbc.fbc..............
        ...........fbc.fbc..............
        ..........ffbcffbc..............
        .........fbbbfbbbc..............
        ..........ccc.ccc...............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `],
    150,
    true
    )
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Enemy, function (sprite, otherSprite) {
    tiles.placeOnRandomTile(otherSprite, assets.tile`myTile15`)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (tiburon.isHittingTile(CollisionDirection.Bottom)) {
        tiburon.vy = -180
    }
})
scene.onHitWall(SpriteKind.Enemy, function (sprite, location) {
    if (sprite.isHittingTile(CollisionDirection.Right)) {
        sprite.vx = -50
        animation.runImageAnimation(
        sprite,
        [img`
            . . . . . . . . . f f . . . . . 
            . . . . . . . . f 6 f . . . . . 
            . . . . . f f f 6 6 f f . . . . 
            . . . . f 6 6 6 8 8 8 6 f . . . 
            . . . f 6 1 1 8 8 8 8 8 6 f . . 
            . . f f 6 f 1 8 8 8 8 8 8 6 f . 
            . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
            . . f f f f f f 6 6 f 8 8 8 6 f 
            . . . . . . 8 6 f 6 f f 8 8 8 f 
            . . . . . . 8 f 8 f f . f 8 8 f 
            . . . . . 8 . . 8 . . . f 8 f . 
            . . . 8 . 8 . . . 8 . f f 8 f . 
            . . . 8 8 . . . . 8 f 8 8 f . . 
            . . . . . . . . . . 8 f 8 f . . 
            . . . . . . . . . 8 8 . f . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . f f . . . . . 
            . . . . . . . . f 6 f . . . . . 
            . . . . . f f f 6 6 f f . . . . 
            . . . . f 6 6 6 8 8 8 6 f . . . 
            . . . f 6 1 1 8 8 8 8 8 6 f . . 
            . . f f 6 f 1 8 8 8 8 8 8 6 f . 
            . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
            . . f f f f f f 6 6 f 8 8 8 6 f 
            . . . . . . 8 6 f 6 f f 8 8 8 f 
            . . . . . . 8 f 8 f f . f 8 8 f 
            . . . . . . 8 . 8 . . . f 8 f . 
            . . . . . . 8 . 8 . . f f 8 f . 
            . . . . . . 8 . 8 . f 8 8 f . . 
            . . . . . . 8 . 8 . . f 8 f . . 
            . . . . . 8 8 8 8 . . . f . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . f f . . . . . 
            . . . . . . . . f 6 f . . . . . 
            . . . . . f f f 6 6 f f . . . . 
            . . . . f 6 6 6 8 8 8 6 f . . . 
            . . . f 6 1 1 8 8 8 8 8 6 f . . 
            . . f f 6 f 1 8 8 8 8 8 8 6 f . 
            . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
            . . f f f f f f 6 6 f 8 8 8 6 f 
            . . . . . . 8 6 f 6 f f 8 8 8 f 
            . . . . . . 8 f 8 f f . f 8 8 f 
            . . . . . . . 8 . . . . f 8 f . 
            . . . . . 8 . 8 . . . f f 8 f . 
            . . . . . 8 8 . 8 . f 8 8 f . . 
            . . . . . . . . . 8 . f 8 f . . 
            . . . . . . . . 8 8 . . f . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . . . f f . . . . . 
            . . . . . . . . f 6 f . . . . . 
            . . . . . f f f 6 6 f f . . . . 
            . . . . f 6 6 6 8 8 8 6 f . . . 
            . . . f 6 1 1 8 8 8 8 8 6 f . . 
            . . f f 6 f 1 8 8 8 8 8 8 6 f . 
            . f 6 6 6 8 8 8 8 8 8 8 8 6 f . 
            . . f f f f f f 6 6 f 8 8 8 6 f 
            . . . . . . 8 6 f 6 f f 8 8 8 f 
            . . . . . . 8 f 8 f f . f 8 8 f 
            . . . . . . 8 . 8 . . . f 8 f . 
            . . . . . . 8 . 8 . . f f 8 f . 
            . . . . . . 8 . 8 . f 8 8 f . . 
            . . . . . . 8 . 8 . . f 8 f . . 
            . . . . . 8 8 8 8 . . . f . . . 
            . . . . . . . . . . . . . . . . 
            `],
        150,
        true
        )
    } else if (sprite.isHittingTile(CollisionDirection.Left)) {
        sprite.vx = 50
        animation.runImageAnimation(
        sprite,
        [img`
            . . . . . f f . . . . . . . . . 
            . . . . . f 6 f . . . . . . . . 
            . . . . f f 6 6 f f f . . . . . 
            . . . f 6 8 8 8 6 6 6 f . . . . 
            . . f 6 8 8 8 8 8 1 1 6 f . . . 
            . f 6 8 8 8 8 8 8 1 f 6 f f . . 
            . f 6 8 8 8 8 8 8 8 8 6 6 6 f . 
            f 6 8 8 8 f 6 6 f f f f f f . . 
            f 8 8 8 f f 6 f 6 8 . . . . . . 
            f 8 8 f . f f 8 f 8 . . . . . . 
            . f 8 f . . . 8 . . 8 . . . . . 
            . f 8 f f . 8 . . . 8 . 8 . . . 
            . . f 8 8 f 8 . . . . 8 8 . . . 
            . . f 8 f 8 . . . . . . . . . . 
            . . . f . 8 8 . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . f f . . . . . . . . . 
            . . . . . f 6 f . . . . . . . . 
            . . . . f f 6 6 f f f . . . . . 
            . . . f 6 8 8 8 6 6 6 f . . . . 
            . . f 6 8 8 8 8 8 1 1 6 f . . . 
            . f 6 8 8 8 8 8 8 1 f 6 f f . . 
            . f 6 8 8 8 8 8 8 8 8 6 6 6 f . 
            f 6 8 8 8 f 6 6 f f f f f f . . 
            f 8 8 8 f f 6 f 6 8 . . . . . . 
            f 8 8 f . f f 8 f 8 . . . . . . 
            . f 8 f . . . 8 . 8 . . . . . . 
            . f 8 f f . . 8 . 8 . . . . . . 
            . . f 8 8 f . 8 . 8 . . . . . . 
            . . f 8 f . . 8 . 8 . . . . . . 
            . . . f . . . 8 8 8 8 . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . f f . . . . . . . . . 
            . . . . . f 6 f . . . . . . . . 
            . . . . f f 6 6 f f f . . . . . 
            . . . f 6 8 8 8 6 6 6 f . . . . 
            . . f 6 8 8 8 8 8 1 1 6 f . . . 
            . f 6 8 8 8 8 8 8 1 f 6 f f . . 
            . f 6 8 8 8 8 8 8 8 8 6 6 6 f . 
            f 6 8 8 8 f 6 6 f f f f f f . . 
            f 8 8 8 f f 6 f 6 8 . . . . . . 
            f 8 8 f . f f 8 f 8 . . . . . . 
            . f 8 f . . . . 8 . . . . . . . 
            . f 8 f f . . . 8 . 8 . . . . . 
            . . f 8 8 f . 8 . 8 8 . . . . . 
            . . f 8 f . 8 . . . . . . . . . 
            . . . f . . 8 8 . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . f f . . . . . . . . . 
            . . . . . f 6 f . . . . . . . . 
            . . . . f f 6 6 f f f . . . . . 
            . . . f 6 8 8 8 6 6 6 f . . . . 
            . . f 6 8 8 8 8 8 1 1 6 f . . . 
            . f 6 8 8 8 8 8 8 1 f 6 f f . . 
            . f 6 8 8 8 8 8 8 8 8 6 6 6 f . 
            f 6 8 8 8 f 6 6 f f f f f f . . 
            f 8 8 8 f f 6 f 6 8 . . . . . . 
            f 8 8 f . f f 8 f 8 . . . . . . 
            . f 8 f . . . 8 . 8 . . . . . . 
            . f 8 f f . . 8 . 8 . . . . . . 
            . . f 8 8 f . 8 . 8 . . . . . . 
            . . f 8 f . . 8 . 8 . . . . . . 
            . . . f . . . 8 8 8 8 . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        150,
        true
        )
    }
})
sprites.onOverlap(SpriteKind.moneda, SpriteKind.moneda, function (sprite, otherSprite) {
    tiles.placeOnRandomTile(otherSprite, assets.tile`myTile0`)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.moneda, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeScoreBy(1)
})
function todos_delfines () {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    del1 = sprites.create(img`
        . . . . . f f . . . . . . . . 
        . . . . . f 6 f . . . . . . . 
        . . . . f f 6 6 f f f . . . . 
        . . . f 6 8 8 8 6 6 6 f . . . 
        . . f 6 8 8 8 8 8 1 1 6 f . . 
        . f 6 8 8 8 8 8 8 1 f 6 f f . 
        . f 6 8 8 8 8 8 8 8 8 6 6 6 f 
        f 6 8 8 8 f 6 6 f f f f f f . 
        f 8 8 8 f f 6 f 6 8 . . . . . 
        f 8 8 f . f f 8 f 8 . . . . . 
        . f 8 f . . . 8 . 8 . . . . . 
        . f 8 f f . . 8 . 8 . . . . . 
        . . f 8 8 f . 8 . 8 . . . . . 
        . . f 8 f . . 8 . 8 . . . . . 
        . . . f . . . 8 8 8 8 . . . . 
        . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    crear_delfin(del1)
    del2 = sprites.create(img`
        . . . . . f f . . . . . . . . 
        . . . . . f 6 f . . . . . . . 
        . . . . f f 6 6 f f f . . . . 
        . . . f 6 8 8 8 6 6 6 f . . . 
        . . f 6 8 8 8 8 8 1 1 6 f . . 
        . f 6 8 8 8 8 8 8 1 f 6 f f . 
        . f 6 8 8 8 8 8 8 8 8 6 6 6 f 
        f 6 8 8 8 f 6 6 f f f f f f . 
        f 8 8 8 f f 6 f 6 8 . . . . . 
        f 8 8 f . f f 8 f 8 . . . . . 
        . f 8 f . . . 8 . 8 . . . . . 
        . f 8 f f . . 8 . 8 . . . . . 
        . . f 8 8 f . 8 . 8 . . . . . 
        . . f 8 f . . 8 . 8 . . . . . 
        . . . f . . . 8 8 8 8 . . . . 
        . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    crear_delfin(del2)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (tiburon.y < otherSprite.y) {
        tiburon.vy = -100
        del1.vx = 0
        animation.stopAnimation(animation.AnimationTypes.All, otherSprite)
        otherSprite.setImage(img`
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . f f . . . 8 8 . . . 
            . . . . . f 6 f 8 8 8 8 . . . 
            8 . . . f f 6 6 f f f 8 . . . 
            8 8 8 8 6 8 8 8 f 6 f f 6 . . 
            8 8 f 6 8 8 8 8 8 f 6 6 f 6 6 
            8 8 6 8 8 8 8 8 f 8 f 6 f f 6 
            . f 6 8 8 8 8 8 8 8 8 6 6 6 f 
            f 6 8 8 8 f 6 6 f f f f f f . 
            . f f f f f f f 8 8 8 8 . . . 
            `)
        pause(200)
        sprites.destroy(otherSprite)
    } else {
        daño()
    }
})
let dirección = ""
let moneda: Sprite = null
let nivel = 0
let del2: Sprite = null
let del1: Sprite = null
let mono: Sprite = null
let tiburon: Sprite = null
scene.setBackgroundColor(9)
tiles.setCurrentTilemap(tilemap`nivel2`)
tiburon = sprites.create(img`
    ..............fffc..............
    ..............fbddcc............
    ..ccc.........ffbddbc...........
    ..cbbc.........fcbbccf..........
    ...cbdc.......ffccccccfffffff...
    ...fbdc....fffffbbbbbbbbbbbbcff.
    ....fbdc.fffffffbbbbcbbbbbbbbbcf
    ....fcdfffffffffbcbcbbbffbbbbcbf
    ....fcbbcfffffffbcbcbbbff1111bbf
    ...fcbbcffffffffbbcbb11111111bf.
    ...fbbffffffff11bbbb11bc33cccf..
    ..fbbf..fffff222cbbb111c131cf...
    ..fff....fffff11ccbbc111c33f....
    ..........fffffccbbdf1111ff.....
    ............ffbbbbdffffff.......
    ..............fffffbf...........
    ..............cbf.cbf...........
    ..............cbf.cbf...........
    ..............cbf.cbf...........
    ..............cbffcbff..........
    ..............cbbbfbbbf.........
    ...............ccc.ccc..........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
mono = sprites.create(img`
    . . . f f f f f f . . . . . . . 
    . . f d e e e d e f . . . . . . 
    . f d f d e d f d e f . . . . . 
    . f d f d e d f d e f f . . . . 
    . f e d e e e d e e d d f . . . 
    c e e f f e e e e e b d c . . . 
    c d d d d d d e e e b d c . . . 
    c c c c c c d d e e f c . . . . 
    . f d d d d d e e f f . . . . . 
    . . f e e e f f e e e f . . . . 
    . . f f f f f e e e e e f . . . 
    . . f d b f e e f f e e f . . . 
    . f f d d f e f f e e e f . . . 
    . f f f f f f e b b f e f . . . 
    . f d d f e e e d d b e f . . . 
    . . f f f f f f f f f f . . . . 
    `, SpriteKind.Meta)
del1 = sprites.create(img`
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
del2 = sprites.create(img`
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
controller.moveSprite(tiburon, 100, 0)
tiburon.ay = 300
tiles.placeOnRandomTile(mono, assets.tile`myTile2`)
tiles.placeOnRandomTile(tiburon, assets.tile`myTile1`)
info.setLife(3)
info.setScore(0)
nivel = 0
game.onUpdate(function () {
    if (tiburon.tileKindAt(TileDirection.Bottom, assets.tile`myTile`) || tiburon.y >= 1590) {
        daño()
    }
    if (!(controller.anyButton.isPressed())) {
        animation.stopAnimation(animation.AnimationTypes.All, tiburon)
        if (dirección == "izquierda") {
            tiburon.setImage(img`
                ..............cfff..............
                ............ccddbf..............
                ...........cbddbff.........ccc..
                ..........fccbbcf.........cbbc..
                ...fffffffccccccff.......cdbc...
                .ffcbbbbbbbbbbbbfffff....cdbf...
                fcbbbbbbbbbcbbbbfffffff.cdbf....
                fbcbbbbffbbbcbcbfffffffffdcf....
                fbb1111ffbbbcbcbfffffffcbbcf....
                .fb11111111bbcbbffffffffcbbcf...
                ..fccc33cb11bbbb11ffffffffbbf...
                ...fc131c111bbbc222fffff..fbbf..
                ....f33c111cbbcc11fffff....fff..
                .....ff1111fdbbccfffff..........
                .......ffffffdbbbbff............
                ...........fbfffff..............
                ...........fbc.fbc..............
                ...........fbc.fbc..............
                ...........fbc.fbc..............
                ..........ffbcffbc..............
                .........fbbbfbbbc..............
                ..........ccc.ccc...............
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                `)
        } else {
            tiburon.setImage(img`
                ..............fffc..............
                ..............fbddcc............
                ..ccc.........ffbddbc...........
                ..cbbc.........fcbbccf..........
                ...cbdc.......ffccccccfffffff...
                ...fbdc....fffffbbbbbbbbbbbbcff.
                ....fbdc.fffffffbbbbcbbbbbbbbbcf
                ....fcdfffffffffbcbcbbbffbbbbcbf
                ....fcbbcfffffffbcbcbbbff1111bbf
                ...fcbbcffffffffbbcbb11111111bf.
                ...fbbffffffff11bbbb11bc33cccf..
                ..fbbf..fffff222cbbb111c131cf...
                ..fff....fffff11ccbbc111c33f....
                ..........fffffccbbdf1111ff.....
                ............ffbbbbdffffff.......
                ..............fffffbf...........
                ..............cbf.cbf...........
                ..............cbf.cbf...........
                ..............cbf.cbf...........
                ..............cbffcbff..........
                ..............cbbbfbbbf.........
                ...............ccc.ccc..........
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                `)
        }
    }
    if (!(tiburon.isHittingTile(CollisionDirection.Bottom))) {
        if (dirección == "izquierda") {
            if (tiburon.vy > 0) {
                tiburon.setImage(img`
                    ..............cfff..............
                    ............ccddbf..............
                    ...........cbddbff.........ccc..
                    ..........fccbbcf.........cbbc..
                    ...fffffffccccccff.......cdbc...
                    .ffcbbbbbbbbbbbbfffff....cdbf...
                    fcbbbbbbbbbcbbbbfffffff.cdbf....
                    fbcbbbbffbbbcbcbfffffffffdcf....
                    fbb1111ffbbbcbcbfffffffcbbcf....
                    .fb11111111bbcbbffffffffcbbcf...
                    ..fccc33cb11bbbb11ffffffffbbf...
                    ...fc131c111bbbc222fffff..fbbf..
                    ....f33c111cbbcc11fffff....fff..
                    .....ff1111fdbbccfffff..........
                    .......ffffffdbbbbff............
                    ...........fbfffff..............
                    ..........fbc.fbc...............
                    ..........fbc.fbc...............
                    .......f.fbf.fbc................
                    ......fbfbfbfbc.................
                    .......cbbccbbc.................
                    ........cc..cc..................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    `)
            } else if (tiburon.vy < 0) {
                tiburon.setImage(img`
                    ..............cfff..............
                    ............ccddbf..............
                    ...........cbddbff.........ccc..
                    ..........fccbbcf.........cbbc..
                    ...fffffffccccccff.......cdbc...
                    .ffcbbbbbbbbbbbbfffff....cdbf...
                    fcbbbbbbbbbcbbbbfffffff.cdbf....
                    fbcbbbbffbbbcbcbfffffffffdcf....
                    fbb1111ffbbbcbcbfffffffcbbcf....
                    .fb11111111bbcbbffffffffcbbcf...
                    ..fccc33cb11bbbb11ffffffffbbf...
                    ...fc131c111bbbc222fffff..fbbf..
                    ....f33c111cbbcc11fffff....fff..
                    .....ff1111fdbbccfffff..........
                    .......ffffffdbbbbff............
                    ...........fbfffff..............
                    ............fbc.fbc.............
                    .............fbc.fbc............
                    ..............fbc.fbc...........
                    ..............fbc.fbc...........
                    .............fbc.fbc............
                    ............fbc.fbc.............
                    .............f...c..............
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    `)
            }
        } else {
            if (tiburon.vy > 0) {
                tiburon.setImage(img`
                    ..............fffc..............
                    ..............fbddcc............
                    ..ccc.........ffbddbc...........
                    ..cbbc.........fcbbccf..........
                    ...cbdc.......ffccccccfffffff...
                    ...fbdc....fffffbbbbbbbbbbbbcff.
                    ....fbdc.fffffffbbbbcbbbbbbbbbcf
                    ....fcdfffffffffbcbcbbbffbbbbcbf
                    ....fcbbcfffffffbcbcbbbff1111bbf
                    ...fcbbcffffffffbbcbb11111111bf.
                    ...fbbffffffff11bbbb11bc33cccf..
                    ..fbbf..fffff222cbbb111c131cf...
                    ..fff....fffff11ccbbc111c33f....
                    ..........fffffccbbdf1111ff.....
                    ............ffbbbbdffffff.......
                    ..............fffffbf...........
                    ...............cbf.cbf..........
                    ...............cbf.cbf..........
                    ................cbf.fbf.f.......
                    .................cbfbfbfbf......
                    .................cbbccbbc.......
                    ..................cc..cc........
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    `)
            } else if (tiburon.vy < 0) {
                tiburon.setImage(img`
                    ..............fffc..............
                    ..............fbddcc............
                    ..ccc.........ffbddbc...........
                    ..cbbc.........fcbbccf..........
                    ...cbdc.......ffccccccfffffff...
                    ...fbdc....fffffbbbbbbbbbbbbcff.
                    ....fbdc.fffffffbbbbcbbbbbbbbbcf
                    ....fcdfffffffffbcbcbbbffbbbbcbf
                    ....fcbbcfffffffbcbcbbbff1111bbf
                    ...fcbbcffffffffbbcbb11111111bf.
                    ...fbbffffffff11bbbb11bc33cccf..
                    ..fbbf..fffff222cbbb111c131cf...
                    ..fff....fffff11ccbbc111c33f....
                    ..........fffffccbbdf1111ff.....
                    ............ffbbbbdffffff.......
                    ..............fffffbf...........
                    .............cbf.cbf............
                    ............cbf.cbf.............
                    ...........cbf.cbf..............
                    ...........cbf.cbf..............
                    ............cbf.cbf.............
                    .............cbf.cbf............
                    ..............c...f.............
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    `)
            }
        }
    }
})
